### ISSUE TITLE
auth checklist

### ISSUE THREAD

**Issue by astudillome** [astudillome/News-Aggregator#3]
- [x] Step 1 — Installing Packages
- [x] Step 2 — Creating the Main App File
- [x] Step 3 — Adding Routes
- [x] Step 4 — Creating Templates
- [x] Step 5 — Creating User Models
- [x] Step 6 — Configuring the Database
- [x] Step 7 — Setting Up the Authorization Function
- [x] Step 8 — Testing the Sign Up Method
- [x] Step 9 — Adding the Login Method
- [x] Step 10 — Protecting Pages
